### ISSUE TITLE
Kickoff session

### ISSUE THREAD

**Issue by victorkane** [victorkane/lit-drupal-lean#3]
Initial meeting with enough brainstorming to open the first batch of user stories for the initial backlog (Milestone 1). 
**Toolset checklist:**
- [x] #4 lit-drupal-lean process workflow chart.
- [x] #5 Nature of Structured User Stories so we don't need so many labels and we can avoid an atomic explosion of tasks.
- [x] #9 Persona Template
- [x] #6 User Story Template
- [x] #10 Collaborative Design Guide
- [x] #11 Style Guide Template
- [x] #15 MVP Planning Guide
- [x] #13 Coding Style Guide
- [x] #12 Architecture Document Template
- [x] #14 Risk List Templatee 
- [x] Publish all docs and templates to Wiki (i.e. the Architecture Doc Template should go in the wiki, the Arch Doc itself is an issue, never closed until project "completed", just always in a state of in process (always in view on the KanBan board at the ready).
### Guides
- [x] #5
- [x] #10 (include #4 here too as part of the Guide
- [x] #15
- [x] #13
### Templates
- [x] #9
- [x] #6
- [x] #11
- [x] #12
- [x] #14

At this session we want to brainstorm in order to create the first batch of user stories. As each of the user story issues are opened, the problem statements, assumptions and hypothesis statements will be specified and tested.

We may need to call a break in the meeting while we create Kickoff Milestone issues and/or necessary artifacts. But finally we will be able to specify the user story backlog for Milestone 1.

So when we finish this Kickoff, we can consider the Kickoff Milestone closed and start off Milestone 1 with its backlog.
Actual progress here will be discussed in the comments.

Some Configuration Management as well as Architectural issues (#19 scaffolding and #20 choose base theme) also need to be considered at this time.

**Comment by victorkane** [comment]
For Milestone 1 we just need:
- #21 Drupal codebase installation and maintenance plan
- MVP is User story #8 so that the basic site can be jump started
- #22 Sub-theme created from Zen 7.x-5.x
- #23 Milestone 1 review
- #24 MVP Planning for Milestone 2 (mo' user stories)

We close Kickoff with:
- [x] #26 Create task list query in Eclipse filtered for Milestone 1
